<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">    
            <li>
                <a href="#" style="color:#FF9F1C">STRATAGIES</a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="s_five" style="color:#4DCCBD">The Five Competitive Forces</a>
                    </li>
                        <li>
                        <a  href="s_diam" style="color:#4DCCBD">Michael Porter Diamond Model</a>
                    </li>
                        <li>
                        <a  href="s_vc" style="color:#4DCCBD">Value Chain</a>
                    </li>
                        <li>
                        <a  href="s_cage" style="color:#4DCCBD">The CAGE</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#" style="color:#FF9F1C">BASIC INFOMATION</a>
                <ul class="nav nav-second-level">
                    <li>
                        <a  href="s_com">Group / Company Info</a>
                    </li>
                    <li>
                        <a  href="s_ind">Industry Info</a>
                    </li>
                    <li>
                        <a  href="s_rc">Region / Country Info</a>
                    </li>
                    <li>
                        <a href="s_ps">Material / Product / Service Info</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->