<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
    <a class="navbar-brand page-scroll" href="index.html">International industrial value chain</a>              
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a class="page-scroll" href="signup.html">Sign Up</a>
        </li>
    </ul>
</div>